[package]
name = "emolog"
version = "0.1.2"
edition = "2021"
description = "Emoji based logger for debugging"
license = "MIT"
keywords = ["logger", "emoji"]
repository = "https://github.com/tapanprakasht/emolog"

[dependencies]
